### ISSUE TITLE
Installing Java FX

### ISSUE THREAD

**Issue by rsorto** [ByteHamster/DrawingPad#5]
How do you install Java FX, I am having issues doing that.

**Comment by Prthwy** [comment]
You should be able to download from https://www.oracle.com/technetwork/java/javase/downloads/index.html.

**Comment by ByteHamster** [comment]
Starting with Java 11, javafx is no longer bundled with Java. DrawingPad needs to be updated to be compatible with Java 11. It needs to ship javafx as a dependency.

**Comment by ByteHamster** [comment]
The new version no longer needs JavaFX.
